# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  spotbugs:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Dependencies #see https://github.com/actions/cache/blob/master/examples.md#java---gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: spotbugs-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            spotbugs-gradle-
      - name: spotbugs
        id: spotbugs_checks
        run: ./gradlew spotbugsMain
        continue-on-error: true
      - name: publish spotbugs
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugs/main.xml'
          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Check on failures
#        if: steps.spotbugs_checks.outcome != 'success'
#        run: exit 1